### ISSUE TITLE
Text appears twice

### ISSUE THREAD

**Issue by linboynton** [Global-Health-Engineering/eth-data-stewardship#1]
Hey @larnsce you have a disclaimer copied twice in the prerequisites section

Prior experience in a programming language is not required for this course, but learners who have worked with data science tools such as R, RStudio IDE, Jupyter Notebooks, Python, or VS Code may have an advantage and gain the most from the material.

Happy to see all this course material!!

**Comment by larnsce** [comment]
Thank you! 🌻
